[workspace]
changelog_update = true
publish = false

[changelog]
header = """# Changelog\n
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n"""

[[package]]
name = "lib"
changelog_path = "CHANGELOG.md"

[[package]]
name = "bin"
changelog_path = "CHANGELOG.md"
