name: Benchmark

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark-compare-pr:
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          submodules: true

      - uses: dtolnay/rust-toolchain@0f44b27771c32bda9f458f75a1e241b09791b331 # v1.91.1
        with:
          toolchain: 1.91 # Also defined in workspace Cargo.toml

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - uses: taiki-e/install-action@44c6d64aa62cd779e873306675c7a58e86d6d532 # v2.62.49
        with:
          tool: cargo-criterion # Also defined in scripts/benchmark.sh

      - name: Compare PR results with baseline
        uses: boa-dev/criterion-compare-action@adfd3a94634fe2041ce5613eb7df09d247555b87 # v3.2.4
        with:
          branchName: ${{ github.base_ref || github.ref_name }}
          benchName: "criterion_benches"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Run benchmarks on main and publish criterion output to GitHub Pages
  benchmark-publish-history:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          submodules: true

      - uses: dtolnay/rust-toolchain@0f44b27771c32bda9f458f75a1e241b09791b331 # v1.91.1
        with:
          toolchain: 1.91 # Also defined in workspace Cargo.toml

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - uses: taiki-e/install-action@44c6d64aa62cd779e873306675c7a58e86d6d532 # v2.62.49
        with:
          tool: cargo-criterion # Also defined in scripts/benchmark.sh

      - name: Run main benchmarks
        # Also in benchmark.yml
        run: |
          cargo bench --bench criterion_benches --color never
      - name: Publish Criterion HTML + JSON to gh-pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/criterion
          destination_dir: benchmark-history
          keep_files: true

      - name: Publish baseline JSON for PR comparison
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/criterion
          destination_dir: benchmark-data/latest
          keep_files: true
