name: Generate documentation

on:
  push:
    branches: [main]

permissions: {}

env:
  CARGO_TERM_COLOR: always
  RUST_DOC_SCOPE: --all-features

jobs:
  documentation-generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          submodules: true

      - uses: dtolnay/rust-toolchain@0f44b27771c32bda9f458f75a1e241b09791b331 # v1.91.1
        with:
          toolchain: 1.91 # Also defined in workspace Cargo.toml

      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1

      - name: Generate documentation
        run: ./scripts/documentation-generate.sh
