name: Generate Documentation

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_DOC_SCOPE: --all-features

jobs:
  documentation-generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.91 # Also defined in workspace Cargo.toml
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Generate documentation
        run: ./scripts/documentation-generate.sh
