name: Check lints

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: {}

env:
  CARGO_TERM_COLOR: always
  RUST_SCOPE: --all-targets --all-features

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          submodules: true

      - uses: dtolnay/rust-toolchain@0f44b27771c32bda9f458f75a1e241b09791b331 # v1.91.1
        with:
          toolchain: 1.91 # Also defined in workspace Cargo.toml
          components: clippy

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - uses: taiki-e/install-action@44c6d64aa62cd779e873306675c7a58e86d6d532 # v2.62.49
        with:
          tool: cargo-workspace-lints # Also defined in scripts/lint-check.sh

      - name: Check lints
        run: ./scripts/lint-check.sh
