name: Nightly

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 4 * * *" # Nightly, 4 AM UTC

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUST_SCOPE: --all-targets --all-features

jobs:
  test:
    name: Test Rust ${{ matrix.toolchain }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - "1.92" # Also defined in workspace Cargo.toml
          - beta
          - nightly
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          submodules: true

      - uses: dtolnay/rust-toolchain@9bc92bc5598b4f3bec5d910d352094982cb0c3b9 # v1.92
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          key: ${{ matrix.os }}-${{ matrix.toolchain }}

      - uses: taiki-e/install-action@44c6d64aa62cd779e873306675c7a58e86d6d532 # v2.62.49
        with:
          tool: cargo-workspace-lints, cargo-nextest, cargo-llvm-cov # Also defined in scripts/lint-check.sh

      - name: Run doctests
        run: cargo test --doc

      - name: Run tests
        run: cargo llvm-cov nextest --workspace $RUST_SCOPE

      - name: Run tests (release)
        run: cargo llvm-cov nextest --release --workspace $RUST_SCOPE

      - name: Check formatting
        run: ./scripts/format-check.sh
        # No need to run on every OS
        if: matrix.os == 'ubuntu-latest'

      - name: Check lints
        run: ./scripts/lint-check.sh
        # No need to run on every OS
        if: matrix.os == 'ubuntu-latest'
