name: Check semantic versioning

on:
  pull_request:
    branches: [main]

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  semver-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          submodules: true

      - uses: dtolnay/rust-toolchain@0f44b27771c32bda9f458f75a1e241b09791b331 # v1.91.1
        with:
          toolchain: 1.91 # Also defined in workspace Cargo.toml

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - name: Check semver compatibility - template_lib
        continue-on-error: true
        uses: obi1kenobi/cargo-semver-checks-action@5b298c9520f7096a4683c0bd981a7ac5a7e249ae # v2.8
        with:
          package: template_lib
          baseline: origin/main

      - name: Check semver compatibility - template_bin
        continue-on-error: true
        uses: obi1kenobi/cargo-semver-checks-action@5b298c9520f7096a4683c0bd981a7ac5a7e249ae # v2.8
        with:
          package: template_bin
          baseline: origin/main
