name: Check Semantic Versioning

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.91 # Also defined in workspace Cargo.toml
          override: true

      - name: Check semver compatibility - lib
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          package: lib

      - name: Check semver compatibility - bin
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          package: bin
